[package]
name = "advent-of-code-2023"
description = "Advent of Code 2023"
authors = ["Marcel Frey <marcelfrey29@mailbox.org>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
