name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo fmt --check
    - name: Build
      run: cargo build
    - name: Run Tests
      run: cargo test
    - name: Cargo Clippy
      run: cargo clippy --all-targets --all-features
